### PR TITLE
sig: add recovery id & v

### LINKED ISSUE #35: Rerturn recovery param on sign (v,r,s)
https://bitcoin.stackexchange.com/questions/38351/ecdsa-v-r-s-what-is-v

https://ethereum.stackexchange.com/questions/13778/get-public-key-of-any-ethereum-account

### PR DESCRIPTION
**Pull request by q9f**
adds recovery id to signatures which can be later used to compute `v`.
- implements `recovery_id` for generic signatures
- implements `v` for ethereum (eip-155)
- implements ethereum `personal_sign`

fix #35

### CODE REVIEW

**Comment by q9f** [comment]
recovery id works but the issue is `k`, we need a determistic `k` not random

* https://github.com/ethereum/eth-keys/blob/master/eth_keys/backends/native/ecdsa.py#L93-L106
* https://crystal-lang.org/api/1.3.2/OpenSSL/HMAC.html

**Comment by q9f** [comment]
@cserb mind taking a look? :)

**Comment by cserb** [comment]
Nice! The crystal lib has "the v" now :)
LGTM

**Comment by q9f** [comment]
part of #57

**Pull request closed without merging**
